# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:forest-service/API-WeatherForecast.git"
          source_branch: "main"
          # destination_repo: "git@github.techtrend.us:dkuffar/-DemoSync_forest-service_API-WeatherForecast.git"
          destination_repo: "git@github.com:almw/wapi-demo.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          # github_token: ${{ secrets.PAT }}
